CREATE TABLE `seasonal_browse_items` (
	`season` text NOT NULL,
	`year` integer NOT NULL,
	`page` integer NOT NULL,
	`sort_order` integer NOT NULL,
	`anilist_id` integer NOT NULL,
	`title_romaji` text NOT NULL,
	`title_english` text,
	`title_native` text,
	`cover_image_large` text NOT NULL,
	`cover_image_medium` text NOT NULL,
	`banner_image` text,
	`format` text NOT NULL,
	`status` text NOT NULL,
	`episodes` integer,
	`average_score` integer,
	`genres_json` text NOT NULL,
	`description` text,
	`season_value` text NOT NULL,
	`season_year` integer NOT NULL,
	`start_year` integer,
	`start_month` integer,
	`start_day` integer,
	`next_airing_at` integer,
	`next_airing_episode` integer,
	`next_airing_time_until` integer,
	`studios_json` text NOT NULL,
	`sync_run_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	PRIMARY KEY(`season`, `year`, `anilist_id`)
);
